"""
DOCX formatter for report generation.
"""

from pathlib import Path
from typing import Dict, Any

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False
    Document = None

from src.formatters.base_formatter import BaseFormatter


class DocxFormatter(BaseFormatter):
    """
    Formatter for Microsoft Word DOCX output format.
    
    Generates professional Word documents with:
    - Proper formatting
    - Headings and styles
    - Tables
    - Images (for diagrams)
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        if not DOCX_AVAILABLE:
            self.logger.warning("python-docx not available. DOCX formatting will be limited.")
    
    def format_report(
        self,
        sections: Dict[str, Any],
        diagrams: Dict[str, Any],
        citations: Dict[str, Any],
        output_path: Path
    ) -> Path:
        """
        Format report as DOCX.
        
        Args:
            sections: Report sections
            diagrams: Generated diagrams
            citations: Citations and references
            output_path: Output file path
            
        Returns:
            Path to generated DOCX file
        """
        if not DOCX_AVAILABLE:
            raise ImportError("python-docx is required for DOCX formatting. Install with: pip install python-docx")
        
        self.logger.info(f"Formatting report as DOCX: {output_path}")
        
        output_path = self._validate_output_path(output_path)
        
        # Create document
        doc = Document()
        
        # Add title page
        self._add_title_page(doc, sections)
        
        # Add table of contents
        if self.config.get("include_table_of_contents", True):
            self._add_table_of_contents(doc)
        
        # Add sections
        self._add_sections(doc, sections)
        
        # Add diagrams
        if diagrams:
            self._add_diagrams_section(doc, diagrams)
        
        # Add references
        if citations.get("references_section"):
            self._add_references(doc, citations)
        
        # Save document
        doc.save(str(output_path))
        
        self.logger.info(f"DOCX report saved to: {output_path}")
        return output_path
    
    def _add_title_page(self, doc: Document, sections: Dict[str, Any]):
        """Add title page to document."""
        title = self.config.get("title", "Technical Report")
        
        # Title
        title_paragraph = doc.add_paragraph()
        title_run = title_paragraph.add_run(title)
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        doc.add_paragraph()  # Empty line
        
        # Subtitle
        subtitle = doc.add_paragraph("Automated Technical Report")
        subtitle_run = subtitle.add_run()
        subtitle_run.font.size = Pt(14)
        subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        doc.add_paragraph()  # Empty line
        
        # Generation info
        info = doc.add_paragraph("Generated by Report Generator")
        info_run = info.add_run()
        info_run.font.italic = True
        info_run.font.size = Pt(10)
        info.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        # Add page break
        doc.add_page_break()
    
    def _add_table_of_contents(self, doc: Document):
        """Add table of contents."""
        toc_heading = doc.add_heading("Table of Contents", level=1)
        
        # This is a simple TOC - in a real implementation, you'd use Word's built-in TOC
        toc_items = [
            "Abstract",
            "Introduction", 
            "Methodology",
            "Results",
            "Discussion",
            "Conclusion",
            "References"
        ]
        
        for item in toc_items:
            p = doc.add_paragraph(item, style='List Number')
        
        doc.add_page_break()
    
    def _add_sections(self, doc: Document, sections: Dict[str, Any]):
        """Add report sections to document."""
        section_order = ["abstract", "introduction", "methodology", "results", "discussion", "conclusion"]
        
        for section_name in section_order:
            if section_name in sections:
                # Add heading
                doc.add_heading(section_name.title(), level=2)
                
                # Add content
                content = sections[section_name]
                self._add_formatted_text(doc, content)
                
                doc.add_paragraph()  # Spacing
    
    def _add_diagrams_section(self, doc: Document, diagrams: Dict[str, Any]):
        """Add diagrams section."""
        if "metadata" not in diagrams:
            return
        
        doc.add_heading("Diagrams", level=2)
        
        for diagram_name, diagram_content in diagrams.items():
            if diagram_name != "metadata" and diagram_content:
                # Add diagram heading
                doc.add_heading(diagram_name.replace('_', ' ').title(), level=3)
                
                # Add diagram as code block (simplified - in reality you'd render Mermaid)
                p = doc.add_paragraph("Diagram:")
                p.add_run(f"\n{diagram_content}").font.name = 'Courier New'
                
                doc.add_paragraph()
    
    def _add_references(self, doc: Document, citations: Dict[str, Any]):
        """Add references section."""
        doc.add_heading("References", level=2)
        
        references_text = citations.get("references_section", "")
        # Remove markdown formatting
        references_text = references_text.replace("# References", "").strip()
        
        self._add_formatted_text(doc, references_text)
    
    def _add_formatted_text(self, doc: Document, text: str):
        """Add formatted text to document."""
        # Simple text addition - in a real implementation, you'd parse markdown
        paragraphs = text.split('\n\n')
        
        for para in paragraphs:
            if para.strip():
                p = doc.add_paragraph(para.strip())
                
                # Basic formatting
                if para.startswith('##'):
                    # This would be handled by headings above
                    continue
                elif para.startswith('-'):
                    p.style = 'List Bullet'
                elif any(para.startswith(f'{i}.') for i in range(1, 10)):
                    p.style = 'List Number'