"""
PDF formatter for report generation.
"""

from pathlib import Path
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.units import inch
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

from src.formatters.base_formatter import BaseFormatter


class PdfFormatter(BaseFormatter):
    """
    Formatter for PDF output format.
    
    Generates professional PDF documents with:
    - Proper typography
    - Page formatting
    - Headers and footers
    - Tables
    """

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        if not PDF_AVAILABLE:
            self.logger.warning("reportlab not available. PDF formatting will be limited.")
    
    def format_report(
        self,
        sections: Dict[str, Any],
        diagrams: Dict[str, Any],
        citations: Dict[str, Any],
        output_path: Path
    ) -> Path:
        """
        Format report as PDF.
        
        Args:
            sections: Report sections
            diagrams: Generated diagrams
            citations: Citations and references
            output_path: Output file path
            
        Returns:
            Path to generated PDF file
        """
        if not PDF_AVAILABLE:
            raise ImportError("reportlab is required for PDF formatting. Install with: pip install reportlab")
        
        self.logger.info(f"Formatting report as PDF: {output_path}")
        
        output_path = self._validate_output_path(output_path)
        
        # Create PDF document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Get styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=1  # Center
        )
        
        # Build document content
        story = []
        
        # Title page
        story.extend(self._build_title_page(styles, title_style, sections))
        
        # Table of contents
        if self.config.get("include_table_of_contents", True):
            story.extend(self._build_table_of_contents(styles))
        
        # Sections
        story.extend(self._build_sections(styles, sections))
        
        # Diagrams
        if diagrams:
            story.extend(self._build_diagrams_section(styles, diagrams))
        
        # References
        if citations.get("references_section"):
            story.extend(self._build_references(styles, citations))
        
        # Build PDF
        doc.build(story)
        
        self.logger.info(f"PDF report saved to: {output_path}")
        return output_path
    
    def _build_title_page(self, styles, title_style, sections: Dict[str, Any]):
        """Build title page content."""
        story = []
        
        title = self.config.get("title", "Technical Report")
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 12))
        
        story.append(Paragraph("Automated Technical Report", styles['Heading2']))
        story.append(Spacer(1, 24))
        
        story.append(Paragraph("Generated by Report Generator", styles['Italic']))
        story.append(Spacer(1, 48))
        
        story.append(PageBreak())
        
        return story
    
    def _build_table_of_contents(self, styles):
        """Build table of contents."""
        story = []
        
        story.append(Paragraph("Table of Contents", styles['Heading1']))
        story.append(Spacer(1, 12))
        
        toc_items = [
            "Abstract",
            "Introduction",
            "Methodology", 
            "Results",
            "Discussion",
            "Conclusion",
            "References"
        ]
        
        for i, item in enumerate(toc_items, 1):
            story.append(Paragraph(f"{i}. {item}", styles['Normal']))
            story.append(Spacer(1, 6))
        
        story.append(PageBreak())
        
        return story
    
    def _build_sections(self, styles, sections: Dict[str, Any]):
        """Build report sections."""
        story = []
        
        section_order = ["abstract", "introduction", "methodology", "results", "discussion", "conclusion"]
        
        for section_name in section_order:
            if section_name in sections:
                # Section heading
                story.append(Paragraph(section_name.title(), styles['Heading2']))
                story.append(Spacer(1, 12))
                
                # Section content
                content = sections[section_name]
                # Split into paragraphs
                paragraphs = content.split('\n\n')
                
                for para in paragraphs:
                    if para.strip():
                        story.append(Paragraph(para.strip(), styles['Normal']))
                        story.append(Spacer(1, 6))
                
                story.append(Spacer(1, 12))
        
        return story
    
    def _build_diagrams_section(self, styles, diagrams: Dict[str, Any]):
        """Build diagrams section."""
        story = []
        
        story.append(Paragraph("Diagrams", styles['Heading2']))
        story.append(Spacer(1, 12))
        
        for diagram_name, diagram_content in diagrams.items():
            if diagram_name != "metadata" and diagram_content:
                # Diagram heading
                story.append(Paragraph(diagram_name.replace('_', ' ').title(), styles['Heading3']))
                story.append(Spacer(1, 6))
                
                # Diagram content (as code block)
                code_style = ParagraphStyle(
                    'Code',
                    parent=styles['Normal'],
                    fontName='Courier',
                    fontSize=8,
                    leftIndent=20
                )
                
                story.append(Paragraph(diagram_content, code_style))
                story.append(Spacer(1, 12))
        
        return story
    
    def _build_references(self, styles, citations: Dict[str, Any]):
        """Build references section."""
        story = []
        
        story.append(Paragraph("References", styles['Heading2']))
        story.append(Spacer(1, 12))
        
        references_text = citations.get("references_section", "")
        # Remove markdown formatting
        references_text = references_text.replace("# References", "").strip()
        
        # Split into lines and format
        lines = references_text.split('\n')
        for line in lines:
            if line.strip() and not line.startswith('---'):
                story.append(Paragraph(line.strip(), styles['Normal']))
                story.append(Spacer(1, 6))
        
        return story